# Generated by Django 3.1.7 on 2021-04-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SqData',
            fields=[
                ('x', models.FloatField(help_text='Longitude coordinate for squirrel sighting point', max_length=25)),
                ('y', models.FloatField(help_text='Latitude coordinate for squirrel sighting point', max_length=25)),
                ('unique_squirrel_id', models.CharField(help_text='Hectare ID" + "Shift" + "Date" (MMDD) + "Hectare Squirrel Number.', max_length=40, unique=True)),
                ('shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='Value is either "AM" or "PM," to communicate whether the sighting session occurred in the morning or late afternoon', max_length=20)),
                ('date', models.CharField(help_text='Sighting date (format: YYYY-MM-DD)', max_length=10)),
                ('age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Value is either Adult or Juvenile.', max_length=10)),
                ('hectare', models.CharField(blank=True, help_text='ID tag derived from hectare grid', max_length=20)),
                ('hectare_squirrel_number', models.IntegerField(blank=True, help_text='Number within the chronological sequence of squirrel sightings for a discrete sighting session', null=True)),
                ('primary_fur_color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary fur color is either Gray, Cinnamon, or Black.', max_length=30)),
                ('highlight_fur_color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Fur highlights are either Gray, Cinnamon, or Black.', max_length=30)),
                ('combination_of_primary_and_highlight_color', models.CharField(blank=True, help_text='A combination of the previous two columns; this column gives the total permutations of primary and highlight colors observed.', max_length=30)),
                ('color_notes', models.TextField(blank=True, help_text='Sighters occasionally added commentary on the squirrel fur conditions. These notes are provided here.')),
                ('location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Value is either "Ground Plane" or "Above Ground." Sighters were instructed to indicate the location of where the squirrel was when first sighted.', max_length=50)),
                ('above_ground_sighter_measurement', models.CharField(blank=True, help_text='For squirrel sightings on the ground plane, fields were populated with a value of “FALSE.”', max_length=10)),
                ('specific_location', models.TextField(blank=True, help_text='Sighters occasionally added commentary on the squirrel location. These notes are provided here.')),
                ('running', models.BooleanField(default=False, help_text='Squirrel was seen running.')),
                ('chasing', models.BooleanField(default=False, help_text='Squirrel was seen chasing another squirrel.')),
                ('climbing', models.BooleanField(default=False, help_text='Squirrel was seen climbing a tree or other environmental landmark.')),
                ('eating', models.BooleanField(default=False, help_text='Squirrel was seen eating.')),
                ('foraging', models.BooleanField(default=False, help_text='Squirrel was seen foraging for food.')),
                ('other_activities', models.TextField(blank=True)),
                ('kuks', models.BooleanField(default=False, help_text='Squirrel was heard kukking, a chirpy vocal communication used for a variety of reasons.')),
                ('quaas', models.BooleanField(default=False, help_text='Squirrel was heard quaaing, an elongated vocal communication which can indicate the presence of a ground predator such as a dog.')),
                ('moans', models.BooleanField(default=False, help_text='Squirrel was heard moaning, a high-pitched vocal communication which can indicate the presence of an air predator such as a hawk.')),
                ('tail_flags', models.BooleanField(default=False, help_text="Squirrel was seen flagging its tail. Flagging is a whipping motion used to exaggerate squirrel's size and confuse rivals or predators. Looks as if the squirrel is scribbling with tail into the air.")),
                ('tail_twitches', models.BooleanField(default=False, help_text='Squirrel was seen twitching its tail. Looks like a wave running through the tail, like a breakdancer doing the arm wave. Often used to communicate interest, curiosity.')),
                ('approaches', models.BooleanField(default=False, help_text='Squirrel was seen approaching human, seeking food.')),
                ('indifferent', models.BooleanField(default=False, help_text='Squirrel was indifferent to human presence.')),
                ('runs_from', models.BooleanField(default=False, help_text='Squirrel was seen running from humans, seeing them as a threat.')),
                ('other_interactions', models.TextField(blank=True, help_text='Sighter notes on other types of interactions between squirrels and humans.')),
                ('lat_long', models.CharField(blank=True, help_text='Insert as "POINT (Latitude Value Longitude Value)"', max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
