# Generated by Django 3.1.7 on 2021-04-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210404_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqdata',
            name='above_ground_sighter_measurement',
            field=models.CharField(blank=True, help_text='For squirrel sightings on the ground plane, fields were populated with a value of “FALSE.”', max_length=10),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Value is either Adult or Juvenile.', max_length=10),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='approaches',
            field=models.BooleanField(default=False, help_text='Squirrel was seen approaching human, seeking food.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='chasing',
            field=models.BooleanField(default=False, help_text='Squirrel was seen chasing another squirrel.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='climbing',
            field=models.BooleanField(default=False, help_text='Squirrel was seen climbing a tree or other environmental landmark.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='color_notes',
            field=models.TextField(blank=True, help_text='Sighters occasionally added commentary on the squirrel fur conditions. These notes are provided here.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='combination_of_primary_and_highlight_color',
            field=models.CharField(blank=True, help_text='A combination of the previous two columns; this column gives the total permutations of primary and highlight colors observed.', max_length=30),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='date',
            field=models.DateField(help_text='Sighting date (format: YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='eating',
            field=models.BooleanField(default=False, help_text='Squirrel was seen eating.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='foraging',
            field=models.BooleanField(default=False, help_text='Squirrel was seen foraging for food.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='hectare',
            field=models.CharField(blank=True, help_text='ID tag derived from hectare grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='hectare_squirrel_number',
            field=models.IntegerField(blank=True, help_text='Number within the chronological sequence of squirrel sightings for a discrete sighting session'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='highlight_fur_color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Fur highlights are either Gray, Cinnamon, or Black.', max_length=30),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='indifferent',
            field=models.BooleanField(default=False, help_text='Squirrel was indifferent to human presence.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='kuks',
            field=models.BooleanField(default=False, help_text='Squirrel was heard kukking, a chirpy vocal communication used for a variety of reasons.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='lat_long',
            field=models.CharField(blank=True, help_text='Sighting coordinates; latitute x longitude.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Value is either "Ground Plane" or "Above Ground." Sighters were instructed to indicate the location of where the squirrel was when first sighted.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='moans',
            field=models.BooleanField(default=False, help_text='Squirrel was heard moaning, a high-pitched vocal communication which can indicate the presence of an air predator such as a hawk.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='other_interactions',
            field=models.TextField(blank=True, help_text='Sighter notes on other types of interactions between squirrels and humans.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='primary_fur_color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary fur color is either Gray, Cinnamon, or Black.', max_length=30),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='quaas',
            field=models.BooleanField(default=False, help_text='Squirrel was heard quaaing, an elongated vocal communication which can indicate the presence of a ground predator such as a dog.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='running',
            field=models.BooleanField(default=False, help_text='Squirrel was seen running.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='runs_from',
            field=models.BooleanField(default=False, help_text='Squirrel was seen running from humans, seeing them as a threat.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='Value is either "AM" or "PM," to communicate whether the sighting session occurred in the morning or late afternoon', max_length=20),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='specific_location',
            field=models.TextField(blank=True, help_text='Sighters occasionally added commentary on the squirrel location. These notes are provided here.'),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='tail_flags',
            field=models.BooleanField(default=False, help_text="Squirrel was seen flagging its tail. Flagging is a whipping motion used to exaggerate squirrel's size and confuse rivals or predators. Looks as if the squirrel is scribbling with tail into the air."),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='tail_twitches',
            field=models.BooleanField(default=False, help_text='Squirrel was seen twitching its tail. Looks like a wave running through the tail, like a breakdancer doing the arm wave. Often used to communicate interest, curiosity.'),
        ),
    ]
