# Generated by Django 3.1.7 on 2021-04-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210412_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqdata',
            name='hectare_squirrel_number',
            field=models.IntegerField(blank=True, help_text='Number within the chronological sequence of squirrel sightings for a discrete sighting session', null=True),
        ),
    ]
