# Generated by Django 3.1.7 on 2021-04-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210412_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqdata',
            name='unique_squirrel_id',
            field=models.CharField(help_text='Hectare ID" + "Shift" + "Date" (MMDD) + "Hectare Squirrel Number.', max_length=40, unique=True),
        ),
    ]
