# Generated by Django 3.1.7 on 2021-04-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210412_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqdata',
            name='lat_long',
            field=models.CharField(blank=True, help_text='Insert as "POINT (Latitude Value Longitude Value)"', max_length=50),
        ),
    ]
