# Generated by Django 3.1.7 on 2021-03-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sqdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField(help_text='Longitude coordinate for squirrel sighting point', max_length=25)),
                ('Y', models.IntegerField(help_text='Latitude coordinate for squirrel sighting point', max_length=25)),
                ('unique_sq_id', models.CharField(help_text='Hectare ID" + "Shift" + "Date" (MMDD) + "Hectare Squirrel Number.', max_length=40)),
                ('Hectare', models.CharField(help_text='ID tag derived from hectare grid', max_length=20)),
                ('Shift', models.CharField(help_text='Value is either "AM" or "PM," to communicate whether the sighting session occurred in the morning or late afternoon', max_length=20)),
                ('Date', models.DateField(help_text='Sighting date', max_length=20)),
                ('Hectare_squirrel_number', models.IntegerField(help_text='Number within the chronological sequence of squirrel sightings for a discrete sighting session', max_length=30)),
                ('Age', models.CharField(help_text='Value is either Adult or Juvenile.', max_length=10)),
                ('primary_fur_color', models.CharField(max_length=30)),
                ('highlight_fur_color', models.CharField(max_length=30)),
                ('combination_fur_color', models.CharField(max_length=30)),
                ('colornotes', models.TextField(blank=True)),
                ('location', models.CharField(max_length=50)),
                ('above_ground_sighter_measure', models.CharField(max_length=10)),
                ('specific_location', models.TextField(blank=True)),
                ('running', models.BooleanField()),
                ('chasing', models.BooleanField()),
                ('climbing', models.BooleanField()),
                ('eating', models.BooleanField()),
                ('foraging', models.BooleanField()),
                ('other_activities', models.TextField(blank=True)),
                ('kuks', models.BooleanField()),
                ('Quass', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('tail_flags', models.BooleanField()),
                ('tail_twiches', models.BooleanField()),
                ('approaches', models.BooleanField()),
                ('indifferent', models.BooleanField()),
                ('runs_from', models.BooleanField()),
                ('other_interactions', models.TextField(blank=True)),
                ('lat_long', models.CharField(max_length=50)),
            ],
        ),
    ]
