# Generated by Django 3.1.7 on 2021-04-04 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqdata',
            old_name='auto_increment_id',
            new_name='id',
        ),
    ]
