# Generated by Django 3.1.7 on 2021-03-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210329_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqdata',
            name='x',
            field=models.FloatField(help_text='Longitude coordinate for squirrel sighting point', max_length=25),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='y',
            field=models.FloatField(help_text='Latitude coordinate for squirrel sighting point', max_length=25),
        ),
    ]
