# Generated by Django 3.1.7 on 2021-03-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210329_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqdata',
            name='approaches',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='chasing',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='climbing',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='eating',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='foraging',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='indifferent',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='kuks',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='moans',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='quaas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='running',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='runs_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='tail_flags',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqdata',
            name='tail_twitches',
            field=models.CharField(max_length=50),
        ),
    ]
